name: clang-format check
description: Checks formatting using clang-format

runs:
  using: composite
  steps:
    - name: Install clang-format
      shell: bash
      run: sudo apt-get install -y clang-format

    - name: Run clang-format
      shell: bash
      run: |
        find src tests -name '*.cpp' -o -name '*.h' | \
        xargs clang-format --dry-run --Werror