name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        uses: ./.github/actions/format

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --parallel

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run static lint
        uses: ./.github/actions/lint

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - name: Run unit tests
        uses: ./.github/actions/ctest
        with:
          label: unit
          